apiVersion: v1
kind: Pod
metadata:
  name: react-pod
  labels: 
    app: reactapp
spec:
  containers:
  - name: react-container
    image: 233274203099.dkr.ecr.ap-south-1.amazonaws.com/reactapp:196d162a2ad9347445254eef228a8badf88aada9
    ports:
    - containerPort: 3000

